#!/usr/bin/env bash
# Regenerates the base64 blur placeholders in src/lib/blur-placeholders.ts.
#
# next/image only derives a blurDataURL automatically from *statically imported*
# images. Everything here is referenced by path string (the team roster is data,
# not 29 import statements), so the placeholders have to be baked in by hand.
#
# Each one is the source downsampled to 16px on its long edge and encoded as
# WebP — around 300 bytes of base64, which the browser paints, stretched and
# blurred, while the real file is still in flight.
#
# Requires macOS `sips` and `cwebp` (brew install webp). Re-run after replacing
# any image listed in ROOTS.
set -euo pipefail

cd "$(dirname "$0")/.."

ROOTS=(public/images/teams)
OUT=src/lib/blur-placeholders.ts
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

{
  echo "// Generated by scripts/gen-blur.sh — do not edit by hand."
  echo "// Tiny WebP previews, keyed by public path, painted under an image"
  echo "// while the full-size file loads. Re-run the script after swapping art."
  echo
  echo "export const BLUR_PLACEHOLDERS: Record<string, string> = {"
} > "$OUT"

count=0
while IFS= read -r file; do
  sips -s format png -Z 16 "$file" --out "$TMP/t.png" >/dev/null 2>&1
  cwebp -q 30 -quiet "$TMP/t.png" -o "$TMP/t.webp"
  b64=$(base64 -i "$TMP/t.webp" | tr -d '\n')
  echo "  \"/${file#public/}\": \"data:image/webp;base64,$b64\"," >> "$OUT"
  count=$((count + 1))
done < <(find "${ROOTS[@]}" -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.webp' \) | sort)

echo "};" >> "$OUT"

# The file is generated a line at a time, so hand it to the formatter rather
# than trying to emit Biome-shaped output from the heredoc above.
npx biome format --write "$OUT" >/dev/null

echo "Wrote $count placeholders to $OUT"
